name: Client portal CI

on:
  push:
    branches:
      - dev
      - master
      - rc
      - staging
      - build-test
    paths:
      - "client-portal/**"
      - ".github/workflows/client_portal.yaml"
  pull_request:
    branches:
      - master
      - rc
      - dev
      - apm
      - staging
    paths:
      - "client-portal/**"

jobs:
  client-portal:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: client-portal
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 


          docker buildx imagetools create erxes/client-portal:master --tag  erxes/client-portal:rc
